### ISSUE TITLE
Differentiate extent and size

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-render#20]
Overloading extent to include the size in pages of a book (3 pp vs pp 3-5) is confusing and counterproductive; the former should be medium/size, and medium/size needs to include localities for ranges.

**Comment by opoudjis** [comment]
Actually, we cannot use medium/size, that's used for dimensions like 8vo. We need a new field, next to extent.

**Comment by ronaldtse** [comment]
Agree.

**Comment by opoudjis** [comment]
Just discovered that l10n for Chinese is not coping with mixed Chinese–Latin text: spaces should only be stripped between Chinese characters.
