### ISSUE TITLE
Update Chinese language output to support Traditional and Simplified references

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-render#21]
Right now Relaton::Render produces this i18n output for Chinese:

```xml
RAMSEY, J. K. 和 W. C. MCGREW. Object play in great apes: Studies in nature and captivity. 在： PELLEGRINI, Anthony D. 和 Peter K. SMITH （编辑）： <em>The nature of play: Great apes and humans</em> [electronic resource, 8vo]. 第第3版。 New York, NY: Guilford Press. 2005. 第89–112页。【看过： 2019年9月3日】.
```

The bibliographic practices for Traditional and Simplified Chinese are slightly different:

Traditional:
```
RAMSEY, J. K. 與 MCGREW, W. C.。〈Object play in great apes: Studies in nature and captivity〉。收錄於： PELLEGRINI, Anthony D.、SMITH, Peter K.（編）。《The nature of play: Great apes and humans》［電子資源，8vo］。第3版。 New York, NY： Guilford Press。 2005。 頁89-112。［閱：2019年9月3日］。
```

Simplified:
```
RAMSEY, J. K.，MCGREW, W. C.  Object play in great apes: Studies in nature and captivity. 见： PELLEGRINI, Anthony D.、SMITH, Peter K.（编）. <em>The nature of play: Great apes and humans</em>［电子资源，8vo］. 第3版. New York, NY：Guilford Press 2005. 页89～112.［阅：2019年9月3日］.
```

**Comment by opoudjis** [comment]
This actually raises a *lot* of questions about Chinese localisation, which I'm trying (obviously) to keep as generic as possible, governed by isodoc-i18n, and which was based on the experience of metanorma-iso

* Right now, two generic words in a list are joined by 和. You have Traditional joining two authors (but not two editors!) by 與, and Simplified not joining them by anything. Is that a general rule of lists (e.g. applicable to clauses?) Or just bibliographies?
* Right now, punctuation is localised, but only before or after a Chinese character (第第3版。 New York; 第89–112页。【看过：) You have Traditional overriding that and using 。 as a delimiter throughout, and Simplified not use 。at all. Are you sure about this? GB standards used 。 consistently.
* I localise [ ] as 【 】. You correct that to ［ ］. Is that universally the case?
* Is ～ the universal Simplified localisation of en-dash?

The variation between no-quote, italics and single-guillemot, double-guillemot is something that I think is beyond the scope of localisation; English after all has styles that do different things with quoting journal titles. Is this a bibliographic thing, or more general between Simplified and Traditional?

**Comment by opoudjis** [comment]
I think I'll introduce an i18n of primary and secondary quote, specific to each style. There will be a default rendering of primary and secondary quote (empty, `<em>` in the foregoing), but there can also be language-overrides (〈, 《 for zh-Hant).

**Comment by opoudjis** [comment]
Ordinals for Traditional Chinese not working with twitter-cldr-rb: the rbnf.yaml files are not defined for locales, but are meant to be generic to the language, so the number localisation needs to be reverted to "generic" Chinese.

This is almost certainly an error for Traditional Chinese, and is a bad way of handling locales even in harmless cases like Flemish vs Dutch—I should not have to undo localisation to get results. But given current events at Twitter, now is not a good time to lodge PRs to enhance their functionality...

**Comment by opoudjis** [comment]
和 "foreigners' logical and"

與 "together" is more correct, but is more restricted semantically (e.g. authorship), and is Traditional only.

Both appear between two final items.

Simplified ignores enum comma (verify).

Traditional is hollow dot. Simplified is normal dot, but fullwidth (verify). 

Chinese citation, use fullwidth punct in citation language.

Lenticular/straight bracket is only style difference.

Is ～ the universal Simplified localisation of en-dash? Yes.

**Comment by opoudjis** [comment]
So:

* [ ] Separate label for authorship "and" in relaton-render, realised in zh-Hant as 與
* [ ] Ensure that enumeration comma is used in lists in zh-Hant
* [ ] Confirm whether enumeration comma is used in lists in zh-Hans
* [ ] Do not localise punctuation by context, but impose Chinese full-width punctuation universally (confirmed in W3C.)
* [ ] Confirm use of fulldwidth dot instead of hollow dot in zh-Hant (reportedly to avoid ambiguity with 0 in technical writing)
* [ ] Use straight instead of lenticular bracket, as style difference (confirm)
* [ ] Use tilde instead of en-dash
* [ ] Implement internationalisable secondary and primary quotes in relaton-render
* [ ] Implement single and double guillemots as zh-Hans primary quotes
* [ ] Implement wavy underline as zh-Hant primary quotes, and (somehow) introduce them into Metanorma markup

**Comment by opoudjis** [comment]
Not seeing any indication that the enumeration comma is not used in PRC; see e.g. https://books.google.com.au/books?id=pV59EAAAQBAJ&pg=PT252&lpg=PT252&dq=d%C3%B9nh%C3%A0o&source=bl&ots=NL5i7a5WyZ&sig=ACfU3U3Zy2L9i__UM27wZ3MDMwBMU9Txhg&hl=el&sa=X&ved=2ahUKEwjy36Dplcz7AhXFVHwKHa9zBtQ4ChDoAXoECBwQAw#v=onepage&q=d%C3%B9nh%C3%A0o&f=false on its use in PRC legislation.

**Comment by opoudjis** [comment]
The use of filled dot instead of hollow in technical writing does not appear constrained to Simplified Chinese. 

I would feel more comfortable if the choice of full stop was a customisation option, but I'm deferring that extension until it is needed.

**Comment by opoudjis** [comment]
In order to deal with wavy underline, introducing CSS style attribute to underline element.

**Comment by opoudjis** [comment]
I am not currently implementing underline style in Asciidoctor markup; underline is marked up as `[underline]#xxx#`. If this is felt useful, I will introduce hyphenation, e.g. `[underline-wavy]#xxx#`.
