### ISSUE TITLE
need CI to bind relaton-render to relaton-bib

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-render#31]
relaton-render consumes relaton-bib encodings of bibliographic objects. When relaton-bib is updated, if it changes the fields of objects, that can break relaton-render (and has).

I request that relaton-render CI jobs be triggered by updates to relaton-bib

**Comment by CAMOBAP** [comment]
@opoudjis should we check it on releases only or on master/main too?

**Comment by ronaldtse** [comment]
On main and releases. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis I think it's better to have this check on `relaton-bib` side, in those case developer will note potential issues on early stage https://github.com/relaton/relaton-bib/pull/73
