### ISSUE TITLE
relaton-render failing to release on workflow

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-render#35]
I have assigned ownership of the gem to metanorma and ribose. I keep getting a message that the tag 0.4.5 is already created. I keep deleting the tag, and I keep creating new tags, and they keep barfing.

https://github.com/relaton/relaton-render/actions/runs/3061104845/jobs/4940454481

**Comment by ronaldtse** [comment]
When you add a gem owner, the e-mail recipient needs to acknowledge the addition. I've just acknowledged for both accounts following your addition.

**Comment by opoudjis** [comment]
IT HAS HAPPENED AGAIN

**Comment by CAMOBAP** [comment]
My bad this commit https://github.com/relaton/relaton-render/commit/064be92f6511d7d0be087d34a361595b89c9bc25 is absolutely wrong, reverted it

**Comment by CAMOBAP** [comment]
@ronaldtse I need your help with `gem owner relaton-render --add relaton@ribose.com`. I don't have permissions to achieve this

**Comment by ronaldtse** [comment]
@CAMOBAP @opoudjis this is done now.

> I have assigned ownership of the gem to metanorma and ribose

This is because the Relaton gems are published under the "relaton" user, not "metanorma" or "ribose".
