### ISSUE TITLE
Update rendering rules for citations in ISO documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-render#36]
ISO "technically" uses a "profile" of ISO 690, with additional formatting styles on top.

1.
As per https://github.com/metanorma/iso-690/issues/19 , in the upcoming Amd we will add an element "authoritative identifier":

```
{creators}. {authoritative document id}: _{title}_. ... ... {other access identifiers like DOI, reference identifiers like ISBN... ORCI}
```

And the authoritative identifier always goes before the `_{title}_`, after `{creators}`.

2. ISO Editors use small caps for author names. This is not an ISO 690 requirement, but for their sanity (and ours) we can do that.
3. In ISO 690 we do `{place}: {publisher}` but in the old ISO practice they do `{publisher}, {place}`. We stick with the 690 format here.

**Comment by opoudjis** [comment]
relaton-render will henceforth differentiate `standardidentifier` (to be renamed `authoritative_identifier`) from `other_identifier`.

**Comment by opoudjis** [comment]
Issue being held up by https://github.com/relaton/relaton-render/issues/35
