### ISSUE TITLE
Crash in render/fields/fields.rb with metanorma-ieee document

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-render#46]
From https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/24

Trace:
```
Metanorma XML Syntax: (XML Line 006288:254): character content of element "stage" invalid; must be equal to "approved", "draft", "superseded" or "withdrawn"
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:112:in `role_inflect'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:36:in `role_fields_format'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:12:in `compound_fields_format'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:170:in `block in citations1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `each'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `each_with_object'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `with_index'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `citations1'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:150:in `render_all'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.5.10/lib/isodoc/presentation_function/refs.rb:28:in `references_render'
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ieee-1.0.15/lib/isodoc/ieee/presentation_ref.rb:48:in `references_render'
```

**Comment by ronaldtse** [comment]
The content of the document has not changed since Jan, so it's an implementation bug?

**Comment by opoudjis** [comment]
Potentially a missing plural of a new role like "Authoriser", but if so, that role should not be being surfaced to begin with. Also need to default to using descriptions instead of roles, when defined (outside of "editor", which is well-understood).

**Comment by ronaldtse** [comment]
All IETF RFCs now contain `<role type="authorizer" />`. There are 2 instances of them in the document. We need to fix this ASAP. Thanks.

**Comment by opoudjis** [comment]
Cannot currently replicate: IEEE  P2874 generates correctly.

<img width="583" alt="Screenshot 2023-08-10 at 12 24 52" src="https://github.com/relaton/relaton-render/assets/1911039/dd3f59d8-7b52-42c7-a3bb-4ee3147db90d">

**Comment by opoudjis** [comment]
I have not updated the relevant code recently, so I don't understand why I can't replicate the crash. @ronaldtse please confirm with me steps you took to replicate, but I'm just compiling in metanorma p2876.adoc with latest libraries.

**Comment by opoudjis** [comment]
Whatever the issue is, it is NOT authorizer:

````
      def role_inflect(contribs, role)
        role.nil? || contribs.size.zero? || 
          %w(author publisher distributor
             authorizer).include?(role) and return nil
        number = contribs.size > 1 ? "pl" : "sg"
        @r.i18n.get[role][number] || role
      end
````

I suspect my Relaton cache and Reese's are not in sync: clearing relaton...

**Comment by opoudjis** [comment]
I've replicated the issue now. I have a more secure version of the code about, but curious to see what role is triggering it...

**Comment by opoudjis** [comment]
It's "Chair". 

I was about to get all angry and complain about Chair being put into the role, but I'm delighted to find that 

(a) Chair is appearing in Description, not Role, as I had requested, for OASIS MQTT Version 5.0
(b) I am already doing what I had said I would do, prioritise descriptions over roles where available.

Fixing in relaton-render.

**Comment by opoudjis** [comment]
So if it doesn't find a plural in the i18n file for the role or description, it will use the singular it is given.
